spring.application.name=natk-api
logging.level.org.springframework.security=DEBUG

spring.datasource.url=${JDBC_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:50MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:50MB}

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}

pdf-service.url=${PDF_SERVICE_URL:http://natk-pdf:8080}
ai-service.url=${AI_SERVICE_URL:http://natk-ai:8080}

# === MinIO ===
minio.endpoint.local=http://localhost:9000
minio.endpoint=${MINIO_URL:http://natk-minio:9000}
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
#minio.access-key=minioadmin
#minio.secret-key=minioadmin