spring.application.name=natk_antivirus

# === MinIO ===
minio.endpoint.local=http://localhost:9000
minio.endpoint=${MINIO_URL:http://natk-minio:9000}
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
#minio.access-key=minioadmin
#minio.secret-key=minioadmin

# ClamAV
clamav.host=${CLAMAV_HOST:clamav}
clamav.port=${CLAMAV_PORT:3310}

natk.api.url=${NATK_API_INTERNAL_URL:http://natk-api:8080}